--CN 稅率



維修單號:MT3Q938179
公司:HZ

SELECT  * FROM RPMMT MT WHERE 1=1 AND MT.MTNO='MT3Q938179' AND MT.COMPANYCODE='HZ'

SELECT RPD.VAT_RATE,RPD.*
  FROM DBS_MAJ.RPMPAYBACKDETAIL RPD
 WHERE RPD.MTCOMPANYCODE = 'HZ'
   AND RPD.MTNO IN ('MT3Q938179') 
   AND RPD.VAT_RATE = '13';


--操作區
SELECT RPD.VAT_RATE,RPD.*
  FROM DBS_MAJ.RPMPAYBACKDETAIL RPD
 WHERE RPD.MTCOMPANYCODE = 'HZ'
   AND RPD.MTNO IN (
'MT3Q927497',
'MT3Q927498'
   ) 
AND RPD.VAT_RATE = '13'
AND RPD.COMPANYCODE='HZ'
   


SELECT * FROM RPMMT MT 
WHERE 1=1
AND MT.CUSTOMERABBNAME LIKE '%浙江宇视%'
AND MT.CUSTOMERABBNAME IN ('浙江大华技术','浙江大华智联','浙江大华科技')

--UPDATE SQL   
   
 UPDATE DBS_MAJ.RPMPAYBACKDETAIL RPD SET RPD.VAT_RATE = '16' 
 WHERE 1=1
 AND RPD.MTCOMPANYCODE = 'HZ' 
 AND RPD.MTNO IN (
'MT3Q927497',
'MT3Q927498'
 ) 
 AND RPD.VAT_RATE = '13'
 AND RPD.COMPANYCODE='HZ';

   

-- RPMMT
select MT.VAT_RATE,MT.* from RPMPAYBACKDETAIL mt where mt.companycode='HZ' 
AND MT.MTNO IN ('MT3Q938179')
AND MT.VAT_RATE= '13' ;

---------------------------------------------------------------------------

