-- CN 人員誤刪排程

SELECT * FROM  TBS_MAJ.FIX_PLANNED_WORK PW  WHERE PW.REFERENCE_NO='S200911073' AND PW.EMP_NO='C05317' AND PW.SHIFT_DATE = TO_DATE('210331','YYMMDD');
SELECT * FROM  TBS_MAJ.FIX_FREE_CLOCK_APPLY FCA WHERE FCA.REFERENCE_NO='S200911073' AND FCA.EMP_NO='C05317' AND  FCA.SHIFT_DATE= TO_DATE('210331','YYMMDD');
SELECT * FROM  FIX_FREE_CLOCK_APPLY_DETAIL FCD WHERE FCD.REFERENCE_NO='S200911073' AND FCD.EMP_NO='C05317' AND FCD.SHIFT_DATE= TO_DATE('210331','YYMMDD')  ORDER BY FCD.SHIFT_DATE DESC



-- DCM 

UPDATE TBS_MAJ.FIX_PLANNED_WORK PW
   SET PW.DELETE_FLAG         = 'N',
       PW.UPDATE_DATE         = SYSDATE,
       PW.UPDATE_EMP_NO       = 'SYS',
       PW.UPDATE_COMPANY_CODE = '00'
 WHERE PW.REFERENCE_NO = 'S200911073'
   AND PW.EMP_NO = 'C05317'
   AND PW.SHIFT_DATE = TO_DATE('210331', 'YYMMDD')
  
UPDATE TBS_MAJ.FIX_FREE_CLOCK_APPLY FCA
   SET FCA.APPROVED_STATUS = 'O',
       FCA.DELETE_FLAG     = 'N',
       FCA.APPROVED_TIME   = NULL,
       FCA.APPROVED_EMP_NO = NULL,
       FCA.REJECT_REASON   = NULL
 WHERE FCA.REFERENCE_NO = 'S200911073'
   AND FCA.EMP_NO = 'C05317'
   AND FCA.SHIFT_DATE = TO_DATE('210331', 'YYMMDD')
