-- 退款完還原修


--查看此單時程註記是否結單(PROCESSCODE > 8)
select mt.processcode,mt.* from rpmmt mt where mtno in ('MT3Q103196') and companycode = 'SH';

--若 RPMPAYBACKDETAIL.slipno為空才能做 

SELECT p.slipno,p.* FROM rpmpaybackdetail p WHERE 1=1 AND mtno in ('MT3Q103196') and companycode = 'SH' ;

--備份
SELECT p.slipno,p.* FROM RPMPAYBACKDETAIL p   WHERE     MTNO in ('MT3Q103196') AND MTCOMPANYCODE='SH';
select mt.repaircode,MT.PROCESSCODE,MT.FINISHTIME,MT.FINISHEMPNO,MT.RETURNNO,MT.PAYBACKAMOUNT,MT.PAYBACKCURRENCYCODE,MT.SO_TRANSMIT_FLAG,mt.* from rpmmt mt where mt.mtno in ('MT3Q103196') AND mt.COMPANYCODE='SH';


--[财务]請協助刪除退款資料，謝謝。
SELECT * FROM RPMPAYBACKDETAIL WHERE MTNO in ('MT3Q103196') AND MTCOMPANYCODE='SH';


SELECT * FROM RPMPAYBACKDETAIL pd WHERE MTNO in ('MT3Q103196') AND MTCOMPANYCODE='SH' AND PD.PAYBACKCODE;

--下DCM 記得修改 MT.REPAIRCODE 改成協商換或的維修代碼
UPDATE DBS_MAJ.RPMPAYBACKDETAIL SET PAYBACKCODE ='*' , RA_TRANSMIT_FLAG = 'O'    WHERE     MTNO   in ('MT3Q103196') AND    MTCOMPANYCODE='SH';

 UPDATE DBS_MAJ.RPMMT MT
      SET MT.PROCESSCODE = '8',
          MT.FINISHTIME = NULL,
          MT.FINISHEMPNO  = NULL,
          MT.RETURNNO = NULL,
          MT.PAYBACKAMOUNT = NULL,
          MT.PAYBACKCURRENCYCODE = NULL,
          MT.SO_TRANSMIT_FLAG = NULL 
 WHERE MT.MTNO  in ('MT3Q103196') 
 AND MT.COMPANYCODE='SH';
