
1.SLIPNO要為空 才可以做，不然要 "call out"


SELECT PAYBACKAMOUNT,A.*FROM RPMMT A WHERE MTNO in('MT3Q929259') AND COMPANYCODE='HZ'; 

SELECT A.PAYBACKPRICE,A.SLIPNO,A.ra_transmit_flag,A.* FROM RPMPAYBACKDETAIL A WHERE MTNO in('MT3Q929259') AND MTCOMPANYCODE='HZ';

2. [轉派財務] 請協助刪除單據

SELECT A.PAYBACKPRICE,A.* FROM RPMPAYBACKDETAIL A WHERE MTNO in('MT3Q929259') AND MTCOMPANYCODE='HZ';

3.轉回後下DCM

UPDATE DBS_MAJ.RPMMT SET PAYBACKAMOUNT='206.23' WHERE MTNO in('MT3Q929259') AND COMPANYCODE='HZ';
UPDATE DBS_MAJ.RPMPAYBACKDETAIL SET PAYBACKPRICE='206.23',ra_transmit_flag = 'O' WHERE MTNO in('MT3Q929259') AND MTCOMPANYCODE='HZ';

4.執行 XETPS 確認傳輸註記為 C

5[轉派財務]  資料已重傳，請協助確認，謝謝   
向 FIS 確認 資料是否傳輸正確

