--先建立一個參照物件
--CREATE OR REPLACE TYPE FN_GET_GG_MASTER_OBJ AS OBJECT (
CREATE OR REPLACE TYPE FN_GET_GG_MASTER_OBJ FORCE AS OBJECT ( /*若要調整欄位, 要用此行語法*/
  COMPANYCODE  VARCHAR2(3)  ,
  SONO  VARCHAR2(10)  ,
  SODATE  DATE  ,
  SOTIME  DATE  ,
  EMPNO  VARCHAR2(6)  ,
  CONO  VARCHAR2(10)  ,
  DELIVERYDATE  DATE  ,
  TRANSPORTATIONFEE  NUMBER  ,
  ADJUSTMENTCODE  VARCHAR2(1)  ,
  LSRF_FLAG  VARCHAR2(1)  ,
  LSRF_CONFIRM_FLAG  VARCHAR2(1)  ,
  LSRF_CONFIRM_TIME  DATE  ,
  LSRF_CONFIRM_EMP_NO  VARCHAR2(6)  ,
  LSRF_CONFIRM_EMP_NAME  VARCHAR2(20)  ,
  INVOICE_NO  VARCHAR2(10)  ,
  INVOICE_CHECK_NO  VARCHAR2(4)  ,
  INVOICE_DATE  DATE  ,
  PRE_CASH_DATE  DATE  ,
  E_INVOICE  VARCHAR2(1)  ,
  INVOICE_BATCH_NO  VARCHAR2(10)  ,
  TRANS_PRICEBOARD_TIME  DATE  ,
  PRT_BUYER_FLAG  VARCHAR2(1)  ,
  WH_COMPANY_CODE  VARCHAR2(3)  ,
  SHIP_TO_TERRITORY_CODE  VARCHAR2(4)  ,
  DEV_TRANS_FLAG  VARCHAR2(1)  ,
  ORIGINAL_REF_NO  VARCHAR2(12)  ,
  SALESTYPE  VARCHAR2(3)  ,
  CUSTOMERCODE  NUMBER(12)  ,
  CUSTOMERPONO  VARCHAR2(60)  ,
  DEPTCODE  VARCHAR2(2)  ,
  LOCALFOBTYPE  VARCHAR2(1)  ,
  SALESEMPNO  VARCHAR2(6)  ,
  DEFARPAYMENTTYPECODE  VARCHAR2(1)  ,
  DEFARPAYMENTTYPEDAY  NUMBER(3)  ,
  ARPAYMENTTYPECODE  VARCHAR2(1)  ,
  ARPAYMENTTYPEDATE  NUMBER(3)  ,
  ARCASHDISCOUNT  NUMBER  ,
  REMARK  VARCHAR2(90)  ,
  CURRENCYCODE  VARCHAR2(3)  ,
  EXCHANGERATE  NUMBER  ,
  EXCHANGERATEDATE  DATE  ,
  TAXTYPE  VARCHAR2(1)  ,
  VATRATE  NUMBER  ,
  TOTAL_AMT  NUMBER  ,
  TOTAL_AMT_GST  NUMBER  ,
  FC_TOTAL_AMT  NUMBER  ,
  FC_TOTAL_AMT_GST  NUMBER  ,
  INVOICETYPECODE  NUMBER(12)  ,
  OPENINVOICECODE  VARCHAR2(1)  ,
  INVOICE_COMBINE  VARCHAR2(1)  ,
  INVOICE_AREA_ID  VARCHAR2(3)  ,
  ORDERTYPECODE  VARCHAR2(1)  ,
  ORDERAPPROVEDNO  VARCHAR2(45)  ,
  BDMARK  VARCHAR2(1)  ,
  SMALLMARK  VARCHAR2(5)  ,
  SMALLCHARGE  NUMBER  ,
  NO_BEFORE_THAN_DATE  DATE  ,
  NO_LATER_THAN_DATE  DATE  ,
  ONLINE_ORDER_NO  VARCHAR2(30)  ,
  SURCHARGE  NUMBER  ,
  SURCHARGE_GST  NUMBER  ,
  TRANSPORTATIONTYPECODE  VARCHAR2(1)  ,
  CWD_CUST_PICKUP_AREA  VARCHAR2(10)  ,
  TRANSPORTATIONFEE_GST  NUMBER  ,
  FREIGHT_SYS  NUMBER  ,
  FREIGHT_SYS_GST  NUMBER  ,
  FREIGHT_CHG_COMMENT  VARCHAR2(50)  ,
  FREIGHT_RSN_CODE  VARCHAR2(2)  ,
  DELIVERY_ATTRIBUTE  VARCHAR2(6)  ,
  RESELLER_EMAIL  VARCHAR2(254)  ,
  STORE_NAME  VARCHAR2(90)  ,
  SHIPTO  VARCHAR2(50)  ,
  SHIPTOADDRESSNO  NUMBER(6)  ,
  SHIPTOCONTACTPERSON  VARCHAR2(45)  ,
  SHIPTOPHONEAREANUMBER  VARCHAR2(8)  ,
  SHIPTOPHONENUMBER  VARCHAR2(30)  ,
  SHIPTOPHONEEXTENSION  VARCHAR2(6)  ,
  SHIPTOMOBILE  VARCHAR2(50)  ,
  SHIP_TO_EMAIL  VARCHAR2(254)  ,
  CUSTOMERMOBILE  VARCHAR2(50)  ,
  TEMPORARY_CUST_MARK  VARCHAR2(1)  ,
  TRANSTOMARK  VARCHAR2(1)  ,
  TRANSTO  VARCHAR2(90)  ,
  TRANSTOADDRESSNO  NUMBER(6)  ,
  TRANSTOCONTACTPERSON  VARCHAR2(45)  ,
  TRANSTOPHONEAREANUMBER  VARCHAR2(8)  ,
  TRANSTOPHONENUMBER  VARCHAR2(30)  ,
  TRANSTOPHONEEXTENSION  VARCHAR2(6)  ,
  TRANSTOMOBILE  VARCHAR2(50)  ,
  TRANS_TO_EMAIL  VARCHAR2(254)  ,
  SHOWMONEYMARK  VARCHAR2(1)  ,
  INVOICE_BUYER_NAME  VARCHAR2(90)  ,
  INVOICE_BUYER_GUINO  VARCHAR2(20)  ,
  UPDATE_TIME  DATE  ,
  UPDATE_EMPNO  VARCHAR2(6)  ,
  INVOICE_TYPE  VARCHAR2(3)  ,
  INVOICE_PRINT_FLAG  VARCHAR2(1)  ,
  AR_CAPITAL_COST_RATE  NUMBER(5,4)  ,
  AR_CAPITAL_COST_STD_RATE  NUMBER(5,4)  ,
  FEE_PAYMENT_CODE  VARCHAR2(3)  ,
  PAY_DAYS_RSN_REMARK  VARCHAR2(600)  ,
  DEPARTURE_TYPE_CODE  VARCHAR2(1)  ,
  SOLD_TO_CONTACT_PERSON  VARCHAR2(45)  ,
  SOLD_TO_TELEPHONE  VARCHAR2(38)  ,
  SOLD_TO_ADDRESS_CODE  VARCHAR2(6)  ,
  SHIP_TO_CUST_UNIT_CODE  VARCHAR2(12)  ,
  PRICE_TERM_CODE  VARCHAR2(2)  ,
  TAX_AMOUNT  NUMBER(16,6)  ,
  CREATE_DATE  DATE  ,
  CREATE_COMPANY_CODE  VARCHAR2(3)  ,
  UPDATE_COMPANY_CODE  VARCHAR2(3)  ,
  CITY_NO  VARCHAR2(60)  ,
  SHIPPING_WAY_CODE  VARCHAR2(1)  ,
  VIRTUAL_OPERATION_TYPE  VARCHAR2(1)  ,
  DIRECT_SHIP_COMPANY_CODE  VARCHAR2(3)  ,
  DIRECT_SHIP_NO  VARCHAR2(12)  ,
  OPEN_INVOICE_CODE  VARCHAR2(1)  ,
  INVOICE_FREQUENCY_CODE  VARCHAR2(1)  ,
  SPECIFICATION_SOURCE_TYPE  VARCHAR2(1)  ,
  UNIT_C_SOURCE_TYPE  VARCHAR2(1)  ,
  OPEN_INVOICE_REMARK_OPT  VARCHAR2(9)  ,
  OPEN_INVOICE_REMARK  VARCHAR2(600)  ,
  USE_POINTS  NUMBER(8)  ,
  POINTS_REDEEM_CASH  NUMBER  ,
  POINTS_REDEEM_CASH_GST  NUMBER  ,
  FC_POINTS_REDEEM_CASH  NUMBER  ,
  FC_POINTS_REDEEM_CASH_GST  NUMBER  ,
  PRINT_ITEM_DTL_FLAG  VARCHAR2(1)  ,
  ITEM_LAYER  VARCHAR2(3)  ,
  DELIVERY_WAY_FLAG  VARCHAR2(1),
  CFM_DATE  DATE,
  CFM_TIME  DATE,
  RECOGNIZED_STATUS  VARCHAR2(1)
  ); 
  
--再建立一個暫存表
CREATE TYPE FN_GET_GG_MASTER_OBJ_TEMP AS TABLE OF FN_GET_GG_MASTER_OBJ; 


--最後建立你的function
/*Y220923調整PERIOD_TYPE判斷:單純以時間來查詢, 即選擇訂單確認(O)的時候, 包含已認列的單據也要能查到*/
CREATE OR REPLACE FUNCTION FN_GET_GG_MASTER(
P_COMPANYCODE IN VARCHAR2,
P_SONO IN VARCHAR2,
P_S_DATE IN VARCHAR2,
P_E_DATE IN VARCHAR2,
P_SALESEMPNO IN VARCHAR2,
P_SALESTYPE IN VARCHAR2,
P_DEPTCODE IN VARCHAR2,
P_INVOICE_NO IN VARCHAR2,
P_CONO IN VARCHAR2,
P_ONLINE_ORDER_NO IN VARCHAR2,
/*特殊控制*/
P_PERIOD_TYPE IN VARCHAR2 /*O-表示以訂單確認時間查詢單據, I-表示以已認列時間查詢單據, A-表示皆查詢*/
) 
RETURN FN_GET_GG_MASTER_OBJ_TEMP PIPELINED IS 

  RS FN_GET_GG_MASTER_OBJ_TEMP;
  V_SQL varchar2(10500);
  
BEGIN
  /*DBMS_OUTPUT.ENABLE(5000000) ;*/
  V_SQL := 'WITH';
  /*依訂單確認時間*/
  IF (P_PERIOD_TYPE IS NULL OR P_PERIOD_TYPE <> 'I') THEN 
    V_SQL := V_SQL || 
    ' CFM AS (
       SELECT * 
       FROM SOM_CO_HEAD_CFM SH
      WHERE 1=1';
        IF P_COMPANYCODE IS NOT NULL AND P_COMPANYCODE <> 'ALL_A' THEN 
         V_SQL := V_SQL || ' AND SH.COMPANYCODE = '''||P_COMPANYCODE||'''';
        END IF;
        
        IF P_SONO IS NOT NULL THEN 
         V_SQL := V_SQL || ' AND SH.SONO LIKE '''||P_SONO||'%''';
        END IF;
       
        IF P_S_DATE IS NOT NULL THEN 
         V_SQL := V_SQL || ' AND SH.SODATE >= to_date('''||P_S_DATE||''', ''MMDDYY'')';
        END IF;
       
        IF P_E_DATE IS NOT NULL THEN 
         V_SQL := V_SQL || ' AND SH.SODATE <= to_date('''||P_E_DATE||''', ''MMDDYY'')';
        END IF;
        
        IF P_SALESEMPNO IS NOT NULL THEN 
         V_SQL := V_SQL || ' AND SH.SALESEMPNO = '''||P_SALESEMPNO||'''';
        END IF;
       
        IF P_SALESTYPE IS NOT NULL THEN 
         V_SQL := V_SQL || ' AND SH.SALESTYPE = '''||P_SALESTYPE||'''';
        END IF;
        
        IF P_DEPTCODE IS NOT NULL THEN 
         V_SQL := V_SQL || ' AND SH.DEPTCODE = '''||P_DEPTCODE||'''';
        END IF;
        
        IF P_INVOICE_NO IS NOT NULL THEN 
         V_SQL := V_SQL || ' AND SH.INVOICE_NO LIKE '''||P_INVOICE_NO||'%''';
        END IF;
        
        IF P_CONO IS NOT NULL THEN 
         V_SQL := V_SQL || ' AND SH.CONO = '''||P_CONO||'''';
        END IF;
        
        IF P_ONLINE_ORDER_NO IS NOT NULL THEN 
         V_SQL := V_SQL || ' AND SH.ONLINE_ORDER_NO LIKE '''||P_ONLINE_ORDER_NO||'%''';
        END IF;
  END IF;
  IF (P_PERIOD_TYPE IS NULL OR P_PERIOD_TYPE <> 'I') THEN 
    V_SQL := V_SQL || '),';
  END IF;  
  /*IF (P_PERIOD_TYPE IS NULL OR P_PERIOD_TYPE <> 'O') THEN */
    V_SQL := V_SQL ||
    ' GG AS (
       SELECT * 
       FROM SOMSOHEAD SH
      WHERE 1=1';
        IF P_COMPANYCODE IS NOT NULL AND P_COMPANYCODE <> 'ALL_A' THEN 
         V_SQL := V_SQL || ' AND SH.COMPANYCODE = '''||P_COMPANYCODE||'''';
        END IF;
        
        IF P_SONO IS NOT NULL THEN 
         V_SQL := V_SQL || ' AND SH.SONO LIKE '''||P_SONO||'%''';
        END IF;
        
        IF P_S_DATE IS NOT NULL AND P_E_DATE IS NOT NULL THEN 
          /*依已認列時間*/
          IF (P_PERIOD_TYPE IS NULL OR P_PERIOD_TYPE <> 'O') THEN 
           V_SQL := V_SQL || ' AND SH.SODATE >= to_date('''||P_S_DATE||''', ''MMDDYY'') AND SH.SODATE <= to_date('''||P_E_DATE||''', ''MMDDYY'')';
          ELSE 
          /*依訂單確認時間*/
          V_SQL := V_SQL || ' AND EXISTS (SELECT 1 FROM CFM M WHERE M.COMPANYCODE = SH.COMPANYCODE AND M.SONO = SH.SONO)';
          /*V_SQL := V_SQL || '   AND M.SODATE >= to_date('''||P_S_DATE||''', ''MMDDYY'') AND M.SODATE <= to_date('''||P_E_DATE||''', ''MMDDYY'')';
          V_SQL := V_SQL || ' )';*/
          END IF;
        END IF;
        
        IF P_SALESEMPNO IS NOT NULL THEN 
         V_SQL := V_SQL || ' AND SH.SALESEMPNO = '''||P_SALESEMPNO||'''';
        END IF;
       
        IF P_SALESTYPE IS NOT NULL THEN 
         V_SQL := V_SQL || ' AND SH.SALESTYPE = '''||P_SALESTYPE||'''';
        END IF;
        
        IF P_DEPTCODE IS NOT NULL THEN 
         V_SQL := V_SQL || ' AND SH.DEPTCODE = '''||P_DEPTCODE||'''';
        END IF;
        
        IF P_INVOICE_NO IS NOT NULL THEN 
         V_SQL := V_SQL || ' AND SH.INVOICE_NO LIKE '''||P_INVOICE_NO||'%''';
        END IF;
        
        IF P_CONO IS NOT NULL THEN 
         V_SQL := V_SQL || ' AND SH.CONO = '''||P_CONO||'''';
        END IF;
        
        IF P_ONLINE_ORDER_NO IS NOT NULL THEN 
         V_SQL := V_SQL || ' AND SH.ONLINE_ORDER_NO LIKE '''||P_ONLINE_ORDER_NO||'%''';
        END IF;
  /*END IF;
  IF (P_PERIOD_TYPE IS NULL OR P_PERIOD_TYPE <> 'O') THEN */
    V_SQL := V_SQL || '),';
  /*END IF;*/

    V_SQL := V_SQL || '
    RS AS (';
    /*IF (P_PERIOD_TYPE IS NULL OR P_PERIOD_TYPE <> 'O') THEN */
      V_SQL := V_SQL || '
      SELECT COMPANYCODE, SONO, SODATE, SOTIME, EMPNO, CONO, DELIVERYDATE, TRANSPORTATIONFEE, ADJUSTMENTCODE, 
         LSRF_FLAG, LSRF_CONFIRM_FLAG, LSRF_CONFIRM_TIME, LSRF_CONFIRM_EMP_NO, LSRF_CONFIRM_EMP_NAME, INVOICE_NO, INVOICE_CHECK_NO, INVOICE_DATE, 
         PRE_CASH_DATE, E_INVOICE, INVOICE_BATCH_NO, TRANS_PRICEBOARD_TIME, PRT_BUYER_FLAG, WH_COMPANY_CODE, SHIP_TO_TERRITORY_CODE, DEV_TRANS_FLAG, ORIGINAL_REF_NO, SALESTYPE, CUSTOMERCODE, 
         CUSTOMERPONO, DEPTCODE, LOCALFOBTYPE, SALESEMPNO, DEFARPAYMENTTYPECODE, DEFARPAYMENTTYPEDAY, ARPAYMENTTYPECODE, ARPAYMENTTYPEDATE, ARCASHDISCOUNT, REMARK, CURRENCYCODE, 
         EXCHANGERATE, EXCHANGERATEDATE, TAXTYPE, VATRATE, TOTAL_AMT, TOTAL_AMT_GST, FC_TOTAL_AMT, FC_TOTAL_AMT_GST, INVOICETYPECODE, OPENINVOICECODE, INVOICE_COMBINE, INVOICE_AREA_ID, 
         ORDERTYPECODE, ORDERAPPROVEDNO, BDMARK, SMALLMARK, SMALLCHARGE, NO_BEFORE_THAN_DATE, NO_LATER_THAN_DATE, ONLINE_ORDER_NO, SURCHARGE, SURCHARGE_GST, TRANSPORTATIONTYPECODE, 
         CWD_CUST_PICKUP_AREA, TRANSPORTATIONFEE_GST, FREIGHT_SYS, FREIGHT_SYS_GST, FREIGHT_CHG_COMMENT, FREIGHT_RSN_CODE, DELIVERY_ATTRIBUTE, RESELLER_EMAIL, STORE_NAME, SHIPTO, SHIPTOADDRESSNO, 
         SHIPTOCONTACTPERSON, SHIPTOPHONEAREANUMBER, SHIPTOPHONENUMBER, SHIPTOPHONEEXTENSION, SHIPTOMOBILE, SHIP_TO_EMAIL, CUSTOMERMOBILE, TEMPORARY_CUST_MARK, TRANSTOMARK, TRANSTO, TRANSTOADDRESSNO, 
         TRANSTOCONTACTPERSON, TRANSTOPHONEAREANUMBER, TRANSTOPHONENUMBER, TRANSTOPHONEEXTENSION, TRANSTOMOBILE, TRANS_TO_EMAIL, SHOWMONEYMARK, INVOICE_BUYER_NAME, INVOICE_BUYER_GUINO, 
         UPDATE_TIME, UPDATE_EMPNO, INVOICE_TYPE, INVOICE_PRINT_FLAG, AR_CAPITAL_COST_RATE, AR_CAPITAL_COST_STD_RATE, FEE_PAYMENT_CODE, PAY_DAYS_RSN_REMARK, DEPARTURE_TYPE_CODE, 
         SOLD_TO_CONTACT_PERSON, SOLD_TO_TELEPHONE, SOLD_TO_ADDRESS_CODE, SHIP_TO_CUST_UNIT_CODE, PRICE_TERM_CODE, TAX_AMOUNT, CREATE_DATE, CREATE_COMPANY_CODE, UPDATE_COMPANY_CODE, 
         CITY_NO, SHIPPING_WAY_CODE, VIRTUAL_OPERATION_TYPE, DIRECT_SHIP_COMPANY_CODE, DIRECT_SHIP_NO, OPEN_INVOICE_CODE, INVOICE_FREQUENCY_CODE, SPECIFICATION_SOURCE_TYPE, UNIT_C_SOURCE_TYPE, 
         OPEN_INVOICE_REMARK_OPT, OPEN_INVOICE_REMARK, USE_POINTS, POINTS_REDEEM_CASH, POINTS_REDEEM_CASH_GST, FC_POINTS_REDEEM_CASH, FC_POINTS_REDEEM_CASH_GST, PRINT_ITEM_DTL_FLAG, ITEM_LAYER, DELIVERY_WAY_FLAG
      FROM GG
       WHERE 1=1';
    /*END IF;*/
    IF (P_PERIOD_TYPE IS NULL OR P_PERIOD_TYPE <> 'I') THEN 
      V_SQL := V_SQL || 'UNION ALL';
    END IF;
    IF (P_PERIOD_TYPE IS NULL OR P_PERIOD_TYPE <> 'I') THEN 
      V_SQL := V_SQL || '
      SELECT COMPANYCODE, SONO, SODATE, SOTIME, EMPNO, CONO, DELIVERYDATE, TRANSPORTATIONFEE, ADJUSTMENTCODE, 
         LSRF_FLAG, LSRF_CONFIRM_FLAG, LSRF_CONFIRM_TIME, LSRF_CONFIRM_EMP_NO, LSRF_CONFIRM_EMP_NAME, NULL INVOICE_NO, INVOICE_CHECK_NO, INVOICE_DATE, 
         PRE_CASH_DATE, E_INVOICE, INVOICE_BATCH_NO, TRANS_PRICEBOARD_TIME, PRT_BUYER_FLAG, WH_COMPANY_CODE, SHIP_TO_TERRITORY_CODE, DEV_TRANS_FLAG, ORIGINAL_REF_NO, SALESTYPE, CUSTOMERCODE, 
         CUSTOMERPONO, DEPTCODE, LOCALFOBTYPE, SALESEMPNO, DEFARPAYMENTTYPECODE, DEFARPAYMENTTYPEDAY, ARPAYMENTTYPECODE, ARPAYMENTTYPEDATE, ARCASHDISCOUNT, REMARK, CURRENCYCODE, 
         EXCHANGERATE, EXCHANGERATEDATE, TAXTYPE, VATRATE, TOTAL_AMT, TOTAL_AMT_GST, FC_TOTAL_AMT, FC_TOTAL_AMT_GST, INVOICETYPECODE, OPENINVOICECODE, INVOICE_COMBINE, INVOICE_AREA_ID, 
         ORDERTYPECODE, ORDERAPPROVEDNO, BDMARK, SMALLMARK, SMALLCHARGE, NO_BEFORE_THAN_DATE, NO_LATER_THAN_DATE, ONLINE_ORDER_NO, SURCHARGE, SURCHARGE_GST, TRANSPORTATIONTYPECODE, 
         CWD_CUST_PICKUP_AREA, TRANSPORTATIONFEE_GST, FREIGHT_SYS, FREIGHT_SYS_GST, FREIGHT_CHG_COMMENT, FREIGHT_RSN_CODE, DELIVERY_ATTRIBUTE, RESELLER_EMAIL, STORE_NAME, SHIPTO, SHIPTOADDRESSNO, 
         SHIPTOCONTACTPERSON, SHIPTOPHONEAREANUMBER, SHIPTOPHONENUMBER, SHIPTOPHONEEXTENSION, SHIPTOMOBILE, SHIP_TO_EMAIL, CUSTOMERMOBILE, TEMPORARY_CUST_MARK, TRANSTOMARK, TRANSTO, TRANSTOADDRESSNO, 
         TRANSTOCONTACTPERSON, TRANSTOPHONEAREANUMBER, TRANSTOPHONENUMBER, TRANSTOPHONEEXTENSION, TRANSTOMOBILE, TRANS_TO_EMAIL, SHOWMONEYMARK, INVOICE_BUYER_NAME, INVOICE_BUYER_GUINO, 
         UPDATE_TIME, UPDATE_EMPNO, INVOICE_TYPE, INVOICE_PRINT_FLAG, AR_CAPITAL_COST_RATE, AR_CAPITAL_COST_STD_RATE, FEE_PAYMENT_CODE, PAY_DAYS_RSN_REMARK, DEPARTURE_TYPE_CODE, 
         SOLD_TO_CONTACT_PERSON, SOLD_TO_TELEPHONE, SOLD_TO_ADDRESS_CODE, SHIP_TO_CUST_UNIT_CODE, PRICE_TERM_CODE, TAX_AMOUNT, CREATE_DATE, CREATE_COMPANY_CODE, UPDATE_COMPANY_CODE, 
         CITY_NO, SHIPPING_WAY_CODE, VIRTUAL_OPERATION_TYPE, DIRECT_SHIP_COMPANY_CODE, DIRECT_SHIP_NO, OPEN_INVOICE_CODE, INVOICE_FREQUENCY_CODE, SPECIFICATION_SOURCE_TYPE, UNIT_C_SOURCE_TYPE, 
         OPEN_INVOICE_REMARK_OPT, OPEN_INVOICE_REMARK, USE_POINTS, POINTS_REDEEM_CASH, POINTS_REDEEM_CASH_GST, FC_POINTS_REDEEM_CASH, FC_POINTS_REDEEM_CASH_GST, PRINT_ITEM_DTL_FLAG, ITEM_LAYER, DELIVERY_WAY_FLAG
      FROM CFM
       WHERE 1=1
       AND CFM.RECOGNIZED_STATUS IN (''O'',''S'',''X'',''*'')';
    END IF;
    V_SQL := V_SQL || '
    )
    
    SELECT FN_GET_GG_MASTER_OBJ(
         RS.COMPANYCODE, RS.SONO, RS.SODATE, RS.SOTIME, RS.EMPNO, RS.CONO, RS.DELIVERYDATE, RS.TRANSPORTATIONFEE, RS.ADJUSTMENTCODE, 
         RS.LSRF_FLAG, RS.LSRF_CONFIRM_FLAG, RS.LSRF_CONFIRM_TIME, RS.LSRF_CONFIRM_EMP_NO, RS.LSRF_CONFIRM_EMP_NAME, RS.INVOICE_NO, RS.INVOICE_CHECK_NO, RS.INVOICE_DATE, 
         RS.PRE_CASH_DATE, RS.E_INVOICE, RS.INVOICE_BATCH_NO, RS.TRANS_PRICEBOARD_TIME, RS.PRT_BUYER_FLAG, RS.WH_COMPANY_CODE, RS.SHIP_TO_TERRITORY_CODE, RS.DEV_TRANS_FLAG, RS.ORIGINAL_REF_NO, RS.SALESTYPE, RS.CUSTOMERCODE, 
         RS.CUSTOMERPONO, RS.DEPTCODE, RS.LOCALFOBTYPE, RS.SALESEMPNO, RS.DEFARPAYMENTTYPECODE, RS.DEFARPAYMENTTYPEDAY, RS.ARPAYMENTTYPECODE, RS.ARPAYMENTTYPEDATE, RS.ARCASHDISCOUNT, RS.REMARK, RS.CURRENCYCODE, 
         RS.EXCHANGERATE, RS.EXCHANGERATEDATE, RS.TAXTYPE, RS.VATRATE, RS.TOTAL_AMT, RS.TOTAL_AMT_GST, RS.FC_TOTAL_AMT, RS.FC_TOTAL_AMT_GST, RS.INVOICETYPECODE, RS.OPENINVOICECODE, RS.INVOICE_COMBINE, RS.INVOICE_AREA_ID, 
         RS.ORDERTYPECODE, RS.ORDERAPPROVEDNO, RS.BDMARK, RS.SMALLMARK, RS.SMALLCHARGE, RS.NO_BEFORE_THAN_DATE, RS.NO_LATER_THAN_DATE, RS.ONLINE_ORDER_NO, RS.SURCHARGE, RS.SURCHARGE_GST, RS.TRANSPORTATIONTYPECODE, 
         RS.CWD_CUST_PICKUP_AREA, RS.TRANSPORTATIONFEE_GST, RS.FREIGHT_SYS, RS.FREIGHT_SYS_GST, RS.FREIGHT_CHG_COMMENT, RS.FREIGHT_RSN_CODE, RS.DELIVERY_ATTRIBUTE, RS.RESELLER_EMAIL, RS.STORE_NAME, RS.SHIPTO, RS.SHIPTOADDRESSNO, 
         RS.SHIPTOCONTACTPERSON, RS.SHIPTOPHONEAREANUMBER, RS.SHIPTOPHONENUMBER, RS.SHIPTOPHONEEXTENSION, RS.SHIPTOMOBILE, RS.SHIP_TO_EMAIL, RS.CUSTOMERMOBILE, RS.TEMPORARY_CUST_MARK, RS.TRANSTOMARK, RS.TRANSTO, RS.TRANSTOADDRESSNO, 
         RS.TRANSTOCONTACTPERSON, RS.TRANSTOPHONEAREANUMBER, RS.TRANSTOPHONENUMBER, RS.TRANSTOPHONEEXTENSION, RS.TRANSTOMOBILE, RS.TRANS_TO_EMAIL, RS.SHOWMONEYMARK, RS.INVOICE_BUYER_NAME, RS.INVOICE_BUYER_GUINO, 
         RS.UPDATE_TIME, RS.UPDATE_EMPNO, RS.INVOICE_TYPE, RS.INVOICE_PRINT_FLAG, RS.AR_CAPITAL_COST_RATE, RS.AR_CAPITAL_COST_STD_RATE, RS.FEE_PAYMENT_CODE, RS.PAY_DAYS_RSN_REMARK, RS.DEPARTURE_TYPE_CODE, 
         RS.SOLD_TO_CONTACT_PERSON, RS.SOLD_TO_TELEPHONE, RS.SOLD_TO_ADDRESS_CODE, RS.SHIP_TO_CUST_UNIT_CODE, RS.PRICE_TERM_CODE, RS.TAX_AMOUNT, RS.CREATE_DATE, RS.CREATE_COMPANY_CODE, RS.UPDATE_COMPANY_CODE, 
         RS.CITY_NO, RS.SHIPPING_WAY_CODE, RS.VIRTUAL_OPERATION_TYPE, RS.DIRECT_SHIP_COMPANY_CODE, RS.DIRECT_SHIP_NO, RS.OPEN_INVOICE_CODE, RS.INVOICE_FREQUENCY_CODE, RS.SPECIFICATION_SOURCE_TYPE, RS.UNIT_C_SOURCE_TYPE, 
         RS.OPEN_INVOICE_REMARK_OPT, RS.OPEN_INVOICE_REMARK, RS.USE_POINTS, RS.POINTS_REDEEM_CASH, RS.POINTS_REDEEM_CASH_GST, RS.FC_POINTS_REDEEM_CASH, RS.FC_POINTS_REDEEM_CASH_GST, RS.PRINT_ITEM_DTL_FLAG, RS.ITEM_LAYER,RS.DELIVERY_WAY_FLAG,
         ';
         IF (P_PERIOD_TYPE IS NULL OR P_PERIOD_TYPE <> 'I') 
           THEN 
           V_SQL := V_SQL || '
           CFM.SODATE, CFM.SOTIME, CFM.RECOGNIZED_STATUS';
         ELSE 
           V_SQL := V_SQL || '
           NULL, NULL, NULL';
         END IF;
    V_SQL := V_SQL || ' 
      )
      FROM RS';
    IF (P_PERIOD_TYPE IS NULL OR P_PERIOD_TYPE <> 'I') THEN 
      V_SQL := V_SQL || '
      LEFT JOIN CFM ON CFM.COMPANYCODE = RS.COMPANYCODE AND CFM.SONO = RS.SONO';
    END IF;
    V_SQL := V_SQL || ' 
     WHERE 1=1
  ';
    
  EXECUTE IMMEDIATE V_SQL BULK COLLECT INTO RS;
  
  /*DBMS_OUTPUT.PUT_LINE('SQL:'||V_SQL);*/
  
  FOR i IN 1 .. RS.COUNT
  LOOP
    PIPE ROW( RS(i) );
  END LOOP;
  
END FN_GET_GG_MASTER;