-- Iprp 待儲/在途/保留 三種料品狀態
SELECT * FROM EAI_RECEIPT_QUEUE_MASTER RQ WHERE RQ.SLIP_NO = 'R+3H200817';
SELECT * FROM EAI_UNRTRV_QUEUE_MASTER UQ WHERE UQ.SLIP_NO = 'R+3H200817';
SELECT * FROM IVCGODOWNCOSTLOG  CL WHERE CL.VOUNO = 'R+3H200817' AND CL.ITEMNO = 'CO562'
SELECT * FROM ivcholdingqty hl where hl.itemno = 'CO562'; -- 待儲
SELECT * FROM IVCHOLDINGQTYREC HLR WHERE HLR.VOUCHERNO = 'R+3H200817'; -- 解待儲物理刪除
SELECT * FROM MSTARTICLE WHERE ARTICLENO='ST1000VX001-A00L'

SELECT * FROM eai_stockin_data sd where sd.slip_no = 'R+3H200817'
