-- TW/BC MBS 部門權限

-- 9183 9164
SELECT * FROM SCSEMPDATA WHERE EMPNO IN ('8964') order by empno; --人員清單
SELECT * FROM SCSEMPTODEPT WHERE  EMPNO IN ('8964')  order by empno; --群組
SELECT * FROM SCSEMPTOOBJ WHERE EMPNO IN ('8964') order by empno; --人員權限
SELECT * FROM SCSSUBOBJGROUP WHERE DEPTCODE = 'N7' AND SUBGROUPCODE = 'M_ML_MASTER'
SELECT * FROM SCSDEPT WHERE DEPTCODE='T7'
SELECT * FROM SCSDEPT D WHERE D.DEPTABBNAME LIKE '%維護%'
-- TBS BC 權限 MBS 也要同步加
-- 同步加人員地點
-- 離職人員
UPDATE DBS_MAJ.SCSEMPDATA ED SET ED.PASSWORD = '8964' , ED.DISABLED = 'N' , ED.QUITDATE = NULL WHERE ED.EMPNO IN ('9183') ;

-- 更換部門
UPDATE DBS_MAJ.SCSEMPTODEPT SET DEPTCODE = 'T7' WHERE  EMPNO IN ('8964'); 


SELECT * FROM SCSEMPTOOBJ WHERE  EMPNO IN ('9195') AND SUBGROUPCODE='M_CS_L1';
DELETE DBS_MAJ.SCSEMPTOOBJ WHERE  EMPNO IN ('9195') AND SUBGROUPCODE='M_CS_L1';

SELECT * FROM SCSEMPTODEPT WHERE  DEPTCODE IN ('LR3')
SELECT * FROM SCSEMPTOOBJ WHERE SUBGROUPCODE= 'LBS_USER'

SELECT * FROM SOMCONTACTADDRESS SCA WHERE SCA.ADDRESS_ID IS NULL
SELECT * FROM SCSEMPDATA WHERE EMPNAME='資湘竹'

-- LBS USER
SELECT COMPANYCODE , DEPTCODE , EMPNO , 'M_MT_CSENG' ,  TO_CHAR( SYSDATE,'MM/DD/YYYY HH24:MI:SS') SYS_DATE , '' , 'Y'||TO_CHAR(SYSDATE,'YYMMDD') AS NOTE FROM SCSEMPTODEPT WHERE EMPNO IN ('8964') 
UNION
SELECT COMPANYCODE , DEPTCODE , EMPNO , 'M_MT_SE' ,  TO_CHAR( SYSDATE,'MM/DD/YYYY HH24:MI:SS') SYS_DATE , '' , 'Y'||TO_CHAR(SYSDATE,'YYMMDD') AS NOTE FROM SCSEMPTODEPT WHERE EMPNO IN ('8964')

ORDER BY 3


SELECT COMPANYCODE , DEPTCODE , EMPNO , 'LBS_USER' ,  TO_CHAR( SYSDATE,'MM/DD/YYYY HH24:MI:SS') SYS_DATE , '' , 'Y220527' FROM SCSEMPTODEPT WHERE EMPNO IN ('9183')

SELECT * FROM scs_empdata where emp_no='AC08'
SELECT * FROM fix_empdata where emp_no='AC08'

BC_ISS:P092、AC08 / BC_PM:U075


insert into DBS_MAJ.SCSEMPTOOBJ (COMPANYCODE, DEPTCODE, EMPNO, SUBGROUPCODE, EFFECTIVEDATE, EXPIREDATE, COMMENTS)
values ('20', 'L1', '9195', 'M_MT_LR', to_date('11-06-2020 10:00:00', 'dd-mm-yyyy hh24:mi:ss'), null, '6850');

insert into DBS_MAJ.SCSEMPTOOBJ (COMPANYCODE, DEPTCODE, EMPNO, SUBGROUPCODE, EFFECTIVEDATE, EXPIREDATE, COMMENTS)
values ('26', 'L1', '9195', 'M_CS_L1', to_date('25-02-2019 18:36:17', 'dd-mm-yyyy hh24:mi:ss'), null, '客服一線人員');

insert into DBS_MAJ.SCSEMPTOOBJ (COMPANYCODE, DEPTCODE, EMPNO, SUBGROUPCODE, EFFECTIVEDATE, EXPIREDATE, COMMENTS)
values ('06', 'L1', '9195', 'M_MT_LEADER', to_date('06-03-2019 17:42:00', 'dd-mm-yyyy hh24:mi:ss'), null, 'Y190306');

insert into DBS_MAJ.SCSEMPTOOBJ (COMPANYCODE, DEPTCODE, EMPNO, SUBGROUPCODE, EFFECTIVEDATE, EXPIREDATE, COMMENTS)
values ('20', 'L1', '9195', 'M_MT_LEADER', to_date('06-03-2019 17:42:00', 'dd-mm-yyyy hh24:mi:ss'), null, 'Y190306');

insert into DBS_MAJ.SCSEMPTOOBJ (COMPANYCODE, DEPTCODE, EMPNO, SUBGROUPCODE, EFFECTIVEDATE, EXPIREDATE, COMMENTS)
values ('26', 'L1', '9195', 'M_MT_LEADER', to_date('06-03-2019 17:42:00', 'dd-mm-yyyy hh24:mi:ss'), null, 'Y190306');

insert into DBS_MAJ.SCSEMPTOOBJ (COMPANYCODE, DEPTCODE, EMPNO, SUBGROUPCODE, EFFECTIVEDATE, EXPIREDATE, COMMENTS)
values ('20', 'L1', '9195', 'M_CS_L1', to_date('25-02-2019 15:24:50', 'dd-mm-yyyy hh24:mi:ss'), null, '客服一線人員');

insert into DBS_MAJ.SCSEMPTOOBJ (COMPANYCODE, DEPTCODE, EMPNO, SUBGROUPCODE, EFFECTIVEDATE, EXPIREDATE, COMMENTS)
values ('06', 'L1', '9195', 'M_CS_L1', to_date('25-02-2019 15:24:50', 'dd-mm-yyyy hh24:mi:ss'), null, '客服一線人員');

UPDATE DBS_MAJ.SCSEMPTODEPT SET DEPTCODE = 'L1' WHERE  EMPNO IN ('9195') AND COMPANYCODE='26';


