-- 更改業主

select * from rpm_proprietor where PROP_CODE='SYNNEX';


SELECT MT.PROCESSCODE,MT.* FROM RPMMT MT 
WHERE 1=1
AND MT.MTNO IN (
'MT96917783'
)

SELECT RG.PROP_ID,RG.* FROM RPMRG RG WHERE 1=1 AND RG.REGISTERNO='98051023';
SELECT RF.PROP_NAME,RF.* FROM RPM_FACT_REPAIR  RF WHERE 1=1 AND RF.MT_NO='MT96917783';
SELECT  RFN.PROP_NAME,RFN.* FROM RPM_FACT_REPAIR_NOW  RFN WHERE 1=1 AND RFN.MT_NO='MT96917783';


--UPDATE

UPDATE DBS_MAJ.rpmrg SET prop_id='3' WHERE registerno='98051023' AND COMPANYCODE='20';  
UPDATE DBS_MAJ.rpm_fact_repair_now SET prop_name='非聯強' WHERE MT_NO='MT96917783' AND COMPANY_CODE='20';
UPDATE DBS_MAJ.rpm_fact_repair SET prop_name='非聯強' WHERE MT_NO='MT96917783' AND COMPANY_CODE='20'; 


