--更改客戶簡稱
--QA資訊
維修單號:MT1K910964
掛號單號:90045009
公司:20

select * from rpmmt mt where 1=1 and mt.registerno='90141994'

--先檢查時程
select MT.CUSTOMERABBNAME , MT.*  from DBS_MAJ.rpmmt MT where mtno IN('MT1K910964') and COMPANYCODE='20';
--掛號單據
select CUSTOMERABBNAME,ENDUSER_NAME,charge_abb_name, ENDUSER_TYPE, 20ow_customer from DBS_MAJ.rpmrg RG where registerno IN('90045009') and COMPANYCODE='20';
--檢查是否產生帳務
select COMPANYCODE from DBS_MAJ.RPMPAYBACKDETAIL A where MTNO='MT1K910964' AND MTCOMPANYCODE='20';

select rrr.customer_abb_name,RRR.ENDUSER_TYPE,rrr.* FROM DBS_MAJ.RPM_FACT_REPAIR rrr WHERE MT_NO='MT1K910964' AND COMPANY_CODE='20';

select RNN.ENDUSER_TYPE,RNN.* FROM DBS_MAJ.RPM_FACT_REPAIR_NOW RNN WHERE MT_NO='MT1K910964' AND COMPANY_CODE='20';

--r+ r- 單據
select * from eai_rpmzin_cust where SLIP_NO='R+3Q801022' and COMPANY_CODE='WU' and MT_NO='MT3Q810647';--R+
select * from eai_rpmzout_cust where SLIP_NO='R-3Q712656' and COMPANY_CODE='WU'; --R-

-- 查看客戶是否存在
SELECT * FROM som_customer_master WHERE CUSTOMERMABBNAME='ACERSERVICE';
SELECT * FROM somcustomer WHERE CUSTOMERABBNAME='ACERSERVICE';

-- UPDATE SQL
UPDATE DBS_MAJ.RPMRG SET CUSTOMERABBNAME='ACERSERVICE',charge_abb_name='ACERSERVICE', SHow_customer='ACERSERVICE',ENDUSER_NAME='ACERSERVICE' WHERE REGISTERNO='90045009' AND COMPANYCODE='20';
UPDATE DBS_MAJ.RPMMT SET CUSTOMERABBNAME='ACERSERVICE' WHERE mtno='MT1K910964' AND COMPANYCODE='20';
UPDATE DBS_MAJ.RPM_FACT_REPAIR SET CUSTOMER_ABB_NAME='ACERSERVICE' WHERE MT_NO='MT1K910964' AND COMPANY_CODE='20';
UPDATE DBS_MAJ.RPM_FACT_REPAIR_NOW SET CUSTOMER_ABB_NAME='ACERSERVICE' WHERE MT_NO='MT1K910964' AND COMPANY_CODE='20';


SELECT * from scsempdata where 1=1 and empno='8285'
