-- END_USER 更改客戶簡稱 (經銷商)

ENDUSER_TYPE 
『1』 = END USER
『2』 = 經銷商

MT單:MT1K910964
掛號:90141994
select * from RPMMT MT WHERE 1=1 AND MT.Mtno ='MT1K910964'
SELECT * FROM RPMMT MT WHERE 1=1 AND MT.REGISTERNO IN ('90141994');
SELECT * FROM RPMRG RG WHERE 1=1 AND REGISTERNO IN ('90141994');

檢查客戶名稱

SELECT * FROM som_customer_master WHERE customermname like 'HP(商用產品委託維修)%';
SELECT * FROM somcustomer WHERE CUSTOMERABBNAME='HP_OS';

-- 查詢資訊(備份)

select CUSTOMERABBNAME,ENDUSER_NAME,charge_abb_name, ENDUSER_TYPE, show_customer from DBS_MAJ.rpmrg where registerno IN('90141994') and COMPANYCODE='20';
select CUSTOMERABBNAME from DBS_MAJ.rpmmt where mtno IN('MT1K910964') and COMPANYCODE='20';
select CUSTOMERABBNAME,ENDUSER_NAME,charge_abb_name, ENDUSER_TYPE, show_customer from DBS_MAJ.rpmrg where registerno IN('90141994') and COMPANYCODE='20';

select COMPANYCODE from DBS_MAJ.RPMPAYBACKDETAIL A where MTNO='MT1K910964' AND MTCOMPANYCODE='20';
select * FROM DBS_MAJ.RPM_FACT_REPAIR WHERE MT_NO='MT1K910964' AND COMPANY_CODE='20';
select * FROM DBS_MAJ.RPM_FACT_REPAIR_NOW WHERE MT_NO='MT1K910964' AND COMPANY_CODE='20';

select * from eai_rpmzin_cust where SLIP_NO='R+3Q801022' and COMPANY_CODE='WU' and MT_NO='MT1K910964';--R+
select * from eai_rpmzout_cust where SLIP_NO='R-3Q712656' and COMPANY_CODE='WU'; --R-




-- UPDATE SQL


UPDATE DBS_MAJ.RPMRG SET CUSTOMERABBNAME='HP_OS',charge_abb_name='HP_OS', ENDUSER_TYPE='2', show_customer='HP_OS' WHERE REGISTERNO='90141994' AND COMPANYCODE='20';
UPDATE DBS_MAJ.RPMMT SET CUSTOMERABBNAME='HP_OS' WHERE mtno='MT1K910964' AND COMPANYCODE='20';
UPDATE DBS_MAJ.RPM_FACT_REPAIR SET CUSTOMER_ABB_NAME='HP_OS', ENDUSER_TYPE='2' WHERE MT_NO='MT1K910964' AND COMPANY_CODE='20';
UPDATE DBS_MAJ.RPM_FACT_REPAIR_NOW SET CUSTOMER_ABB_NAME='HP_OS', ENDUSER_TYPE='2' WHERE MT_NO='MT1K910964' AND COMPANY_CODE='20';

update DBS_MAJ.eai_rpmzin_cust set CUST_UNIT_NO='130160',CUST_ABBRV_NAME='武汉蓝之新',CUST_FULL_NAME='武汉市蓝之新电脑有限公司' where SLIP_NO='R+3Q801022' and COMPANY_CODE='WU' and MT_NO='MT3Q810647';
update DBS_MAJ.eai_rpmzout_cust set CUST_UNIT_NO='130160',CUST_ABBRV_NAME='武汉蓝之新',CUST_FULL_NAME='武汉市蓝之新电脑有限公司' where SLIP_NO='R+3Q801022' and COMPANY_CODE='WU';
