-- 服務類型
SELECT DISTINCT SERVICE_TYPE_CODE, SERVICETYPEDESC 
FROM rpm_fact_repair_now
ORDER BY SERVICE_TYPE_CODE

SELECT MT.PROCESSCODE ,MT.SERVICETYPECODE, MT.* FROM RPMMT MT  WHERE 1=1 AND MT.MTNO='MT66948747';

SELECT FR.SERVICE_TYPE_CODE,FR.SERVICETYPEDESC,FR.* FROM RPM_FACT_REPAIR FR WHERE 1=1 AND FR.MT_NO='MT66948747';

SELECT FR.SERVICE_TYPE_CODE,FR.SERVICETYPEDESC,FR.* FROM RPM_FACT_REPAIR_NOW FR WHERE 1=1 AND FR.MT_NO='MT66948747';


UPDATE DBS_MAJ.rpmmt SET SERVICETYPECODE='5' WHERE mtno='MT66948747' AND COMPANYCODE='20';

先確認有無單據資料
UPDATE DBS_MAJ.rpm_fact_repair SET SERVICE_TYPE_CODE='5',SERVICETYPEDESC='5-銷退' WHERE MT_NO='MT66948747' AND COMPANY_CODE='20';
UPDATE DBS_MAJ.rpm_fact_repair_now SET SERVICE_TYPE_CODE='5', SERVICETYPEDESC='5-銷退' WHERE MT_NO='MT66948747' AND COMPANY_CODE='20'; 
