-- 覆修代碼調整

更改為: D-非保修的損壞
人損: Y
SELECT MT.REPEATREASON,MT.MAN_MADE,MT.REPEATMARK,MT.P_COMPANYCODE,MT.P_MTNO,MT.* FROM RPMMT MT WHERE 1=1 AND MT.MTNO='MT3C905846';
SELECT RF.REPEATREASON,RF.MAN_MADE,RF.REPEAT_TYPE,RF.REPEAT_GROUP,RF.REPEAT_DAY,RF.* FROM RPM_FACT_REPAIR RF WHERE 1=1 AND RF.REPEAT_GROUP IS NOT NULL AND RF.MT_NO='MT3C905846';
SELECT RFN.REPEATREASON,RFN.MAN_MADE,RFN.REPEAT_TYPE,RFN.REPEAT_GROUP,RFN.REPEAT_DAY,RFN.* FROM RPM_FACT_REPAIR_NOW RFN WHERE 1=1 AND RFN.MT_NO='MT3C905846';

-- 查看看是否有
SELECT * FROM RPM_FACT_REPAIR WHERE 1=1 AND REPEATREASON='D-非保修的損壞(本次)'

-- 查詢 REPEAT_TYPE (DAMAGETYPEDESC)
SELECT * from rpmdamagecode rc where  damagecode ='D'
select * from rpmdamagetypecode WHERE DAMAGETYPECODE='3'

-- UPDATE SQL

update DBS_MAJ.RPMMT set REPEATREASON='D' , MAN_MADE ='Y' WHERE 1=1 AND MTNO='MT3C905846' AND COMPANYCODE='20'  ;
update DBS_MAJ.RPM_FACT_REPAIR set Repeatreason='D-非保修的損壞(本次)',MAN_MADE ='Y' WHERE 1=1 AND MT_NO='MT3C905846' AND COMPANY_CODE='20'  ;
update DBS_MAJ.RPM_FACT_REPAIR_NOW set Repeatreason='D-非保修的損壞(本次)',MAN_MADE ='Y' WHERE 1=1 AND MT_NO='MT3C905846' AND COMPANY_CODE='20' ;


update DBS_MAJ.RPMMT set REPEATREASON='D' , MAN_MADE ='Y' WHERE 1=1 AND MTNO='MT3C905846' AND COMPANYCODE='20'  ;
update DBS_MAJ.RPM_FACT_REPAIR set Repeatreason='D-非保修的損壞(本次)',MAN_MADE ='Y' WHERE 1=1 AND MT_NO='MT3C905846' AND COMPANY_CODE='20'  ;
update DBS_MAJ.RPM_FACT_REPAIR_NOW set Repeatreason='D-非保修的損壞(本次)',MAN_MADE ='Y' WHERE 1=1 AND MT_NO='MT3C905846' AND COMPANY_CODE='20' ;
