--HK 稅率



維修單號:MT3Q921957
公司:联强杭州-HZ0059-卢剑 

SELECT RPD.VAT_RATE,RPD.*
  FROM DBS_MAJ.RPMPAYBACKDETAIL RPD
 WHERE RPD.MTCOMPANYCODE = 'HK'
   AND RPD.MTNO IN ('MT3Q921957') 
   AND RPD.VAT_RATE = '13';


--操作區
SELECT RPD.VAT_RATE,RPD.*
  FROM DBS_MAJ.RPMPAYBACKDETAIL RPD
 WHERE RPD.MTCOMPANYCODE = 'HK'
   AND RPD.MTNO IN (
   'MT3Q902891'
   ) 
AND RPD.VAT_RATE = '13'
AND RPD.COMPANYCODE='HK'
   


SELECT * FROM RPMMT MT 
WHERE 1=1
AND MT.CUSTOMERABBNAME='浙江大华技术'
AND MT.CUSTOMERABBNAME IN ('浙江大华技术','浙江大华智联','浙江大华科技')

--UPDATE SQL   
   
 UPDATE DBS_MAJ.RPMPAYBACKDETAIL RPD SET RPD.VAT_RATE = '16' 
 WHERE 1=1
 AND RPD.MTCOMPANYCODE = 'HK' 
 AND RPD.MTNO IN (
 'MT3Q902891'
 ) 
 AND RPD.VAT_RATE = '13'
 AND RPD.COMPANYCODE='HK';

   

-- RPMMT
select MT.VAT_RATE,MT.* from RPMPAYBACKDETAIL mt where mt.companycode='NJ' 
AND MT.MTNO IN ('MT3Q908349')
AND MT.VAT_RATE= '13' ;

---------------------------------------------------------------------------

