-- 更改業主

-- 更改業主

-- 更改業主

select PROP_ID ,PROP_CODE from rpm_proprietor where PROP_CODE='ACER';


SELECT MT.PROCESSCODE,MT.* FROM RPMMT MT 
WHERE 1=1
AND MT.COMPANYCODE='HK'
AND MT.MTNO IN (
'MT3Q942540'
)

SELECT * FROM RPMRG RG WHERE 1=1 AND RG.REGISTERNO='90055816';
SELECT * FROM DBS_MAJ.rpm_fact_repair_now WHERE MT_NO='MT3Q942540' AND COMPANY_CODE='HK';
SELECT * FROM DBS_MAJ.rpm_fact_repair WHERE MT_NO='MT3Q942540' AND COMPANY_CODE='HK' AND YYYY_MM ='201908';
-- UPDATE


UPDATE DBS_MAJ.rpmrg SET prop_id='5' WHERE registerno='90055816' AND COMPANYCODE='HK';  
UPDATE DBS_MAJ.rpm_fact_repair_now SET prop_name='ACER' WHERE MT_NO='MT3Q942540' AND COMPANY_CODE='HK';
UPDATE DBS_MAJ.rpm_fact_repair SET prop_name='ACER' WHERE MT_NO='MT3Q942540' AND COMPANY_CODE='HK' AND YYYY_MM ='201908'; 

