-- 還原R-

還原完修 僅R-關聯 

SELECT * FROM RPMMTSWAPOUT  RST WHERE 1=1 AND RST.SWAPOUTVOUCHERNO='R-3Q907531'
SELECT * FROM 

1.  刪除MT換貨紀錄
DELETE DBS_MAJ.RPMMTSWAPOUT WHERE COMPANYCODE='20' AND MTNO='MT96557196'
2. MT 還原完修
