-- CADS 金流

-- 
-- 原
--https%3A%2F%2Fb2buat3.synnex-grp.com%2Finvoke%2FsynnexB2B.model.NewebPay%2FgetPaymentStoreStatus%3FsenderID%3DTW_NEWEB_PAY_UAT%26receiverID%3DTBS_S_TW_UAT%26documentType%3DNewebPay_Response
-- 改
--https%3A%2F%2Fb2buat3.synnex-grp.com%2Finvoke%2FsynnexB2B.model.NewebPay%2FNewebPay_Response%3FsenderID%3DTW_NEWEB_PAY_UAT%26receiverID%3DTBS_S_TW_UAT%26documentType%3DNewebPay_Response
--https%3A%2F%2Fb2buat3.synnex-grp.com%2Finvoke%2FsynnexB2B.model.NewebPay%2FgetPaymentStatus%3FsenderID%3DTW_NEWEB_PAY_UAT%26receiverID%3DTBS_S_TW_UAT%26documentType%3DNewebPay_Response%26
SELECT * FROM TBS_MAJ.MST_BUSINESS_RULE WHERE TABLE_NAME ='CADS' AND TABLE_FIELD LIKE 'BLUE_NEW_JSON_NotifyURL%' FOR UPDATE
-- LK-MS341898044
-- 1K-MS341921171
SELECT * FROM TBS_MAJ.MST_BUSINESS_RULE WHERE TABLE_NAME ='CADS' AND TABLE_FIELD = 'MS341921171'FOR UPDATE
SELECT * FROM TBS_MAJ.MST_BUSINESS_RULE WHERE TABLE_NAME ='CADS' AND TABLE_FIELD LIKE 'MS341898044%' AND TABLE_FIELD_CODE ='APP' FOR UPDATE
SELECT * FROM TBS_MAJ.MST_BUSINESS_RULE WHERE TABLE_NAME ='CADS' AND TABLE_FIELD LIKE 'MS341898044%' AND TABLE_FIELD_CODE ='ERP' FOR UPDATE


SELECT * FROM TBS_MAJ.MST_BUSINESS_RULE WHERE TABLE_NAME ='XBCPR' and table_field = 'REMARK' and table_field_code='GET_NO' FOR UPDATE

SELECT * FROM TBS_MAJ.MST_BUSINESS_RULE WHERE TABLE_NAME ='CADS' and create_emp_no = '8566' and create_Date>= to_Date('2023-03-24','YYYY-MM-DD')  for update 
-- PAY_HTML_PARA
SELECT * FROM TBS_MAJ.MST_BUSINESS_RULE WHERE TABLE_NAME ='CADS' and table_field ='PAY_HTML_PARA';
SELECT * FROM TBS_MAJ.MST_BUSINESS_RULE WHERE TABLE_NAME ='CADS' and table_field ='ABLE_MODFIY_PROCESS';
SELECT * FROM TBS_MAJ.MST_BUSINESS_RULE WHERE TABLE_NAME ='CADS' and table_field ='SUS' FOR UPDATE


-- 期初驗證
SELECT * FROM TBS_MAJ.MST_BUSINESS_RULE WHERE TABLE_NAME ='XBCPR' and table_field ='REMARK';


-- abcdef0123456789
-- 1212pasta2020@@@
SELECT * FROM TBS_MAJ.MST_BUSINESS_RULE WHERE TABLE_NAME ='XILDM' AND TABLE_FIELD = 'AES_TOKEN_KEY' FOR UPDATE


/* i18n */

SELECT * FROM SCS_KEY_SETTING SK WHERE SK.BU_CODE = 'TW' AND SK.KEY_CODE LIKE 'RPM.CADS%' and SK.CREATE_DATE >= TO_dATE('2023-03-20','YYYY-MM-DD') FOR UPDATE

-- MT66300504

SELECT * FROM SUS_CUST_URL_PARAMETER C WHERE C.CREATE_DATE >= TO_dATE('2023-04-10','YYYY-MM-DD') ORDER BY C.CREATE_DATE DESC
SELECT * FROM SUS_CUST_URL U

SELECT * FROM RPMMT MT WHERE MT.CIA_NO IS NOT NULL AND MT.PROCESSCODE ='8'

MS341921171
-- https://tbsmuat.synnex-grp.com:4443/TBS_V/Identity?page=views/eai/cads/cads_main
-- http://192.168.211.145:8080/TBS_V/Identity?page=views/eai/cads/cads_main
-- http://localhost.synnex-grp.com:8080/TBS_V/Identity?page=views/eai/cads/cads_main
SELECT * FROM DBS_MAJ.MST_BUSINESS_RULE WHERE TABLE_NAME ='ETAI' AND TABLE_FIELD ='TBS_S_URL' FOR UPDATE

-- https://tbsmuat.synnex-grp.com:4443/TBS_V/Identity
-- http://localhost.synnex-grp.com:8080/TBS_V/Identity 
SELECT * FROM TBS_MAJ.MST_BUSINESS_RULE WHERE TABLE_NAME ='CADS' AND TABLE_FIELD_CODE ='QR_CODE' FOR UPDATE
SELECT * FROM TBS_MAJ.MST_BUSINESS_RULE WHERE TABLE_NAME ='CADS' AND TABLE_FIELD = 'SUS' FOR UPDATE
SELECT * FROM TBS_MAJ.MST_BUSINESS_RULE WHERE TABLE_NAME ='XILDM' AND TABLE_FIELD = 'SUS' FOR UPDATE


/* AIS 入口*/
SELECT * FROM WEBMETHOD
-- SYNNEX_PAY_TW
-- FPP_TW
-- MS341918769
SELECT * FROM TBS_MAJ.MST_TABLE_MAPPING WHERE TABLE_NAME ='CADS' AND TABLE_FIELD = 'WEBMETHOD' FOR UPDATE
SELECT * FROM TBS_MAJ.MST_BUSINESS_RULE WHERE TABLE_NAME ='XBCPR' AND TABLE_FIELD = 'WEBMETHOD' FOR UPDATE

http://b2buat.au.synnex-grp.com:5555/invoke/synnex.CashFlowBridge.service:payment


-- 交易紀錄
SELECT TR.MERCHANT_ID , TR.PAYMENT_FLAG  ,TR.* FROM DBS_MAJ.RPM_TRADE_RECORD TR WHERE TR.SLIP_NO = 'MT66317646' order by TR.CREATE_TIME DESC 
-- 維修單
SELECT MT.TERMCODE , MT.PAYMENT_TYPE_CODE , MT.CIA_NO , MT.PROCESSCODE , MT.* FROM DBS_MAJ.RPMMT MT WHERE MT.MTNO = 'MT66317646' ;
-- 維修備註
-- 2023/4/11 下午 12:34:29
SELECT * FROM DBS_MAJ.RPMMTREMARK RR WHERE RR.MTNO = 'MT66317646'


SELECT * FROM dbs_maj.rpmmtcharge ch
SELECT * FROM DBS_MAJ.RPM_TRADE_RECORD TR WHERE TR.TRADE_NO = 'MT66300312_03170435'
-- MS341918769
SELECT * FROM DBS_MAJ.RPM_TRADE_RECORD RT WHERE RT.CREATE_TIME >= TRUNC(SYSDATE)
-- MT66300377_03250959
SELECT * FROM DBS_MAJ.RPM_TRADE_RECORD TR WHERE TR.SLIP_NO = 'MT66300377' order by TR.CREATE_TIME DESC
 FOR UPDATE

SELECT * FROM RPM_TRADE_RECORD TR WHERE TR.Trade_No = 'MT66300366_03241152'

 WHERE MT.MTNO = 'MT66300200'
SELECT * FROM DBS_MAJ.RPM_ASSIGN RA WHERE RA.MT_NO = 'MT66300200'
SELECT * FROM DBS_MAJ.RPM_ASSIGN RA WHERE 1=1 
AND RA.CAR_CODE IS NOT NULL
AND EXISTS(
SELECT * FROM DBS_MAJ.RPMMT MT
WHERE 1=1
AND RA.COMPANY_CODE = MT.COMPANYCODE
AND RA.MT_NO = MT.MTNO
AND MT.MAINT_PLACE = 'TC'
)

SELECT * FROM DBS_MAJ.RPM_TRADE_RECORD TR WHERE TR.SLIP_NO = '20230325155007989'

SELECT * FROM DBS_MAJ.RPM_APP_EMP_LOCATION AL WHERE AL.CREATE_DATE >= TRUNC(SYSDATE) -30

SELECT * FROM B2C_PAYMENT_STORE
SELECT * FROM B2C_USABLE_PAYMENT
