-- XBCPR 

-- 交易紀錄檔
SELECT * FROM DBS_MAJ.RPM_TRADE_RECORD RD

/* BUSINESS RULE */
-- 取得藍星商店對映 HASH-KEY/VALUE
SELECT * FROM TBS_MAJ.MST_BUSINESS_RULE WHERE TABLE_NAME = 'XBCPR' AND TABLE_FIELD = 'GET_HASH_INFO';
-- 藍星支付工具轉換代碼 (V:ATM , 5 :信用卡 , Q: 超商繳費)
SELECT * FROM TBS_MAJ.MST_BUSINESS_RULE WHERE TABLE_NAME = 'XBCPR' AND TABLE_FIELD = 'BLUE_NEW_PAYMENT_CHANGE';
-- 藍星wms
-- http://b2buat3.synnex-grp.com:5555/invoke/synnex.JSONService.receive/HttpRelay
-- http://b2buat3.synnex-grp.com:5555/invoke/synnex.JSONService.receive/HttpRelay
SELECT * FROM TBS_MAJ.MST_BUSINESS_RULE WHERE TABLE_NAME = 'XBCPR' AND TABLE_FIELD = 'WEBMETHOD_BlueNew' FOR UPDATE
-- 查詢交易日期內天數
SELECT * FROM TBS_MAJ.MST_BUSINESS_RULE WHERE TABLE_NAME = 'XBCPR' AND TABLE_FIELD = 'FIND_TRADE_DAYS' for update
-- 付款狀態
SELECT * FROM TBS_MAJ.MST_BUSINESS_RULE WHERE TABLE_NAME = 'XBCPR' AND TABLE_FIELD = 'TRADE_PAYMENT_FLAG' for update
-- 成功創建交易紀錄
SELECT * FROM TBS_MAJ.MST_BUSINESS_RULE WHERE TABLE_NAME = 'XBCPR' AND TABLE_FIELD = 'TRADE_RECFLAG' for update

SELECT * FROM TBS_MAJ.MST_BUSINESS_RULE WHERE TABLE_NAME = 'XBCPR' AND TABLE_FIELD = 'TRADE_BS' for update

SELECT * FROM TBS_MAJ.MST_BUSINESS_RULE WHERE TABLE_NAME = 'XBCPR' AND TABLE_FIELD = 'AUTO_QUOTE_COMFIRM_PROCESS' for update

SELECT * FROM TBS_MAJ.MST_BUSINESS_RULE WHERE TABLE_NAME = 'XBCPR' AND TABLE_FIELD = 'DEFAULT_CARRIER_TYPE' for update

SELECT * FROM DBS_MAJ.RPMMT

SELECT * FROM TBS_MAJ.MST_BUSINESS_RULE WHERE TABLE_NAME = 'XBCPR' AND TABLE_FIELD_code = 'PAY_STATUS' for update
SELECT * FROM TBS_MAJ.MST_BUSINESS_RULE WHERE TABLE_NAME = 'XBCPR' AND TABLE_FIELD_code = 'PAY_STATUS' for update

-- https://tbsmuat.synnex-grp.com:4443/TBS_V/Identity?page=views/eai/cads/cads_main
SELECT * FROM DBS_MAJ.MST_BUSINESS_RULE WHERE TABLE_NAME = 'ETAI' AND TABLE_FIELD ='TBS_S_URL' for update

https://tbsmuat.synnex-grp.com:4443/TBS_V/Identity?page=views/eai/cads/cads_main
SELECT * FROM DBS_MAJ.MST_BUSINESS_RULE WHERE TABLE_FIELD LIKE 'BLUE_NEW_PAYMENT_CHANGE_%'

-- http://tpap014t.synnex-grp.com:5555/EAI/One2One 走EAI
SELECT * FROM DBS_MAJ.MST_TABLE_MAPPING WHERE TABLE_NAME = 'COMMON' AND TABLE_FIELD ='WEBMETHOD'

SELECT * FROM TBS_MAJ.MST_TABLE_MAPPING WHERE TABLE_NAME ='COMM' AND TABLE_FIELD ='DEFAULT_BU' for update
SELECT * FROM TBS_MAJ.MST_TABLE_MAPPING WHERE  TABLE_FIELD ='DEFAULT_LANGUAGE' for update


/* i18n */
SELECT * FROM SCS_KEY_SETTING SK WHERE SK.BU_CODE = 'TW' AND SK.KEY_CODE LIKE 'SOM.XBCPR%' and SK.CREATE_DATE >= TO_dATE('2023-03-20','YYYY-MM-DD') FOR UPDATE

SELECT * FROM SCS_KEY_SETTING SK WHERE SK.BU_CODE = 'TW' AND SK.KEY_CODE LIKE 'SOM.XBCPR.CVSINFO'


/* ~~     LOG    ~~  */
-- 藍星CALL BACK
SELECT * FROM TBS_MAJ.EAI_TRANSMIT_MESSAGE_LOG ML WHERE ML.FUNC_CODE = 'XBCPR' AND ML.MESSAGE LIKE 'PAY_STATUS_CALL_BAC%' AND ML.TRANSMIT_TIME >= TO_dATE('2023-03-28 16:30:00','YYYY-MM-DD HH24:MI:SS')  ORDER BY ML.SEQ_NO DESC
-- 排程 : 取得藍星繳費資訊
SELECT * FROM TBS_MAJ.EAI_TRANSMIT_MESSAGE_LOG ML WHERE ML.FUNC_CODE = 'XBCPR' AND ML.MESSAGE LIKE 'SOM_XBCPR_PAY_STATUS%' AND ML.TRANSMIT_TIME >= TO_dATE('2023-03-28 16:30:00','YYYY-MM-DD HH24:MI:SS') ORDER BY ML.SEQ_NO DESC

SELECT * FROM EAI_TRANSMIT_MESSAGE_LOG ML where ML.MESSAGE = 'XBCPR webMethod 傳輸失敗'

SELECT * FROM EAI_TRANSMIT_MESSAGE_LOG ML where ML.TRANSMIT_ID = '340322WXJCK9'
SELECT * FROM EAI_TRANSMIT_LOG EL WHERE EL.FUNC_CODE = 'XBCPR' AND EL.TRANSMIT_TIME >= TO_dATE('2023-03-22','YYYY-MM-DD') 

SELECT * FROM EAI_TRANSMIT_MESSAGE_LOG ML WHERE ML.FUNC_CODE = 'XBCPR' AND ML.TRANSMIT_TIME >= TO_dATE('2023-03-23 15:47:00','YYYY-MM-DD HH24:MI:SS') 
and ML.SEQ_NO > 66716593
ORDER BY ML.SEQ_NO DESC
/* APP LOG */

-- 藍星CALL BACK
SELECT * FROM TBS_MAJ.FIX_APP_LOG AL 
WHERE 1=1 
AND AL.CREATE_TIME >=TO_dATE('2023-03-28 15:40:00','YYYY-MM-DD HH24:MI:SS') 
AND AL.EMP_NO LIKE 'MT66300490%' 
AND AL.METHOD_NAME = 'PAY_STATUS_CALL_BACK' 
AND AL.SEQ_NO > 118980
ORDER BY AL.SEQ_NO DESC

-- 排程:取得藍星繳費資訊

SELECT * FROM TBS_MAJ.FIX_APP_LOG AL 
WHERE 1=1 
AND AL.CREATE_TIME >=TO_dATE('2023-03-22 15:40:00','YYYY-MM-DD HH24:MI:SS') 
--AND AL.EMP_NO LIKE 'MT66300490%' 
AND AL.METHOD_NAME = 'PAY_STATUS_BATCH' 
AND AL.SEQ_NO > 118629
ORDER BY AL.SEQ_NO DESC


/* 交易紀錄&備註 */
SELECT * FROM DBS_MAJ.RPM_TRADE_RECORD RTR WHERE RTR.SLIP_NO LIKE '20230406111558207%' ORDER BY RTR.CREATE_TIME DESC;
SELECT * FROM DBS_MAJ.RPMMTREMARK RMR WHERE RMR.MTNO ='20230406111558207' ORDER BY RMR.SEQNO ;

/* 測試區 */



SELECT TR.REC_FLAG,
       TR.PAYMENT_FLAG,
       TR.SLIP_NO,
       TR.TRADE_NO,
       TR.MERCHANT_ID,
       TR.TICKET_FLAG,
       TR.TICKET_TIME,
       TR.PAYMENT_TIME,
       TR.PAYMENT_TYPE_CODE
  FROM DBS_MAJ.RPM_TRADE_RECORD TR
 WHERE 1=1
 AND TR.SLIP_NO IN ('MT66300386','') 


SELECT * FROM DBS_MAJ.RPMMT MT WHERE MT.MTNO = 'MT66300386';
SELECT * FROM DBS_MAJ.RPMMTREMARK MTR WHERE MTR.MTNO = 'MT66300386';
 -- LK 商店 MS341898044
 
-- LK MT66300328 信用卡
SELECT * FROM DBS_MAJ.RPM_TRADE_RECORD TR WHERE TR.SLIP_NO In('MT66300490') ORDER BY TR.UPDATE_TIME DESC 
FOR UPDATE
UPDATE DBS_MAJ.RPM_TRADE_RECORD TR SET TR.MERCHANT_ID = 'MS341898044' , TR.PAYMENT_FLAG ='O' WHERE TR.SLIP_NO In('MT66300490')
SELECT MT.TOTALAMOUNT , MT.* FROM DBS_MAJ.RPMMT MT WHERE 1=1 AND MT.MTNO = 'MT66300490'
SELECT * FROM DBS_MAJ.RPMMTREMARK R WHERE R.MTNO = 'MT66300490'
SELECT RTR.MERCHANT_ID , RTR.* FROM DBS_MAJ.RPM_TRADE_RECORD RTR WHERE RTR.TRADE_NO = 'MT66300490_03220242' FOR UPDATE


SELECT * FROM DBS_MAJ.RPM_TRADE_RECORD TR WHERE TR.TRADE_NO = 'MT66300490_03230515' FOR UPDATE


SELECT * FROM TBS_MAJ.MST_TABLE_MAPPING WHERE TABLE_NAME = 'SYS_ENV_CONFIG' FOR UPDATE
-- MT66300363

SELECT '本機',
       TR.*
  FROM DBS_MAJ.RPMMT TR
 WHERE 1=1
 AND TR.MTNO IN ('MT66300363','') 
UNION
SELECT 'UAT',
       TR.*
  FROM DBS_MAJ.RPMMT TR
 WHERE 1=1
 AND TR.MTNO IN ('MT66300364','') 

SELECT * FROM RPMMT MT WHERE MT.BELONGEMPNO , MT.QUOTATION_SENDER , MT.APP_EMP_NO




SELECT '本機',
       TR.*
  FROM DBS_MAJ.RPMRG TR
 WHERE 1=1
 AND TR.REGISTERNO IN ('30000375','') 
UNION
SELECT 'UAT',
       TR.*
  FROM DBS_MAJ.RPMRG TR
 WHERE 1=1
 AND TR.REGISTERNO IN ('30000393','') 

報確資料
不一樣欄位

SELECT '本機',
       TR.*
  FROM DBS_MAJ.RPMMTREMARK TR
 WHERE 1=1
 AND TR.MTNO IN ('MT66300328','') 
UNION
SELECT 'UAT',
       TR.*
  FROM DBS_MAJ.RPMMTREMARK TR
 WHERE 1=1
 AND TR.MTNO IN ('MT66300351','') 

