-- 2. 補群還去車程

SELECT FL04.* FROM FIX_APP_EMP_LOCATION FL04,
(
SELECT    
          FL03.COMPANY_CODE,
          FL03.EMP_NO,
          FL03.OPERATION_TYPE,
          FL03.APP_TIME, 
          FL03.APP_SERVER_TIME, 
          FL03.WORK_START_TIME AS "03_WORK_START_TIME", 
          FL03.WORK_LINE_NO,
          FL_NEW.SLIP_NO,
          FL_NEW.FS_EMP_NO,
          FL_NEW.SOLUTIONS_CODE,
          FL_NEW.FS_WORK_START_DATE,
          FL_NEW.WORK_START_TIME,
          FL_NEW.FS_WORK_LINE_NO 
FROM FIX_APP_EMP_LOCATION FL03,
(
  SELECT  FL.EMP_NO AS FL_EMP_NO,
          FL.WORK_START_TIME AS FL_WORK_START_DATE,
          FL.WORK_LINE_NO AS FL_WORK_LINE_NO,
          FS.SLIP_NO,
          FS.EMP_NO AS FS_EMP_NO,
          FS.SOLUTIONS_CODE,
          DECODE(FS.WORK_START_DATE, NULL, FS.LEAD_START_DATE,FS.WORK_START_DATE) AS FS_TIME,--施工時間(起)為主沒有才抓前置作業時間(起)
          FS.LEAD_START_DATE,
          FS.WORK_START_DATE AS FS_WORK_START_DATE,
          FS.WORK_START_TIME,
          FS.WORK_LINE_NO AS FS_WORK_LINE_NO
  FROM FIX_APP_EMP_LOCATION FL,FIX_SERVICE FS
  WHERE 1=1 
  AND FL.EMP_NO=FS.EMP_NO
  AND FL.MT_SLIP_NO=FS.SLIP_NO
  AND FL.WORK_LINE_NO=FS.WORK_LINE_NO
  AND FL.WORK_START_TIME=FS.WORK_START_TIME
  AND FL.OPERATION_TYPE IN('04')
  AND FL.DRIVE_CAL_FLAG='C'
  AND (FS.DRIVE_T_START_DATE IS NULL OR FS.DRIVE_T_END_DATE IS NULL)
  AND SOLUTIONS_CODE='005'
  AND FL.APP_TIME>=TRUNC(SYSDATE-30)
  AND NOT EXISTS  (
  SELECT * FROM FIX_APP_EMP_LOCATION fl2 WHERE 1=1 and fl.work_start_time=fl2.work_start_time AND FL.OPERATION_TYPE IN('11'))
)FL_NEW
WHERE 1=1 
AND FL_NEW.FL_EMP_NO=FL03.EMP_NO
AND FL_NEW.FL_WORK_START_DATE=FL03.WORK_START_TIME
AND FL03.WORK_LINE_NO=FL_NEW.FL_WORK_LINE_NO-1
AND FL03.OPERATION_TYPE IN('03','06')
AND TO_CHAR(FL_NEW.FS_TIME,'dd-mm-yyyy hh24:mi')<=TO_CHAR(FL03.APP_TIME,'dd-mm-yyyy hh24:mi')--不會ADD到秒
)FL_0306
WHERE 1=1 
AND FL_0306.EMP_NO=FL04.EMP_NO
AND FL_0306.WORK_START_TIME=FL04.WORK_START_TIME
AND FL04.WORK_LINE_NO=FL_0306.WORK_LINE_NO+1    
AND FL04.OPERATION_TYPE IN('04');


