--3. 施工開始晚於結束

SELECT OOG.ORG_NAME,
       FE.EMP_NO || '-' || FE.EMP_NAME,
       FS.SLIP_NO,
       TO_CHAR(FS.WORK_START_DATE, 'YYYY-MM-DD HH24:MI'),
       TO_CHAR(EL.APP_SERVER_TIME, 'YYYY-MM-DD HH24:MI'),
       TO_CHAR(FS.WORK_END_DATE, 'YYYY-MM-DD HH24:MI'),
       TO_CHAR(EL2.APP_SERVER_TIME, 'YYYY-MM-DD HH24:MI')
  FROM FIX_SERVICE          FS,
       FIX_APP_EMP_LOCATION EL,
       FIX_APP_EMP_LOCATION EL2,
       FIX_ORG_RELATION_GRP ORG,
       FIX_ORG_ORG_GRP      OOG,
       FIX_EMPDATA          FE
WHERE 1 = 1
   AND FS.WORK_END_DATE < FS.WORK_START_DATE
   AND FS.EMP_NO = EL.EMP_NO(+)
   AND FS.WORK_START_TIME = EL.WORK_START_TIME(+)
   AND FS.WORK_LINE_NO = EL.WORK_LINE_NO(+)
   AND EL.OPERATION_TYPE(+) = '04'
   AND FS.EMP_NO = EL2.EMP_NO(+)
   AND FS.WORK_START_TIME = EL2.WORK_START_TIME(+)
   AND FS.WORK_LINE_NO = EL2.WORK_LINE_NO(+)
   AND EL2.OPERATION_TYPE(+) = '06'
   AND ORG.ORG_OID = OOG.ORG_OID
   AND ORG.BU_ID = OOG.BU_ID
   AND FE.EMP_NO = ORG.EMP_NO
   AND FE.BU_ID = ORG.BU_ID
   AND ORG.EMP_NO = FS.EMP_NO
   AND ORG.RELATION_TYPE = 'E'
   and fs.create_date>=sysdate-10
   and fs.create_date<=sysdate
   ORDER BY OOG.ORG_NAME,EL.EMP_NO,TO_CHAR(FS.WORK_START_DATE, 'YYYY-MM-DD HH24:MI')
