SELECT * FROM MST_TABLE_MAPPING MTM
WHERE 1=1
AND MTM.TABLE_NAME='ITEM_ARM_JGM'
AND MTM.TABLE_FIELD ='currency'



SELECT DISTINCT SOM.GUARANTYSTATUS, SOM.GUARANTYSTATUSDESC, SOM.LINENO
  FROM SOMGUARANTYSTATUSCODE SOM
 WHERE 1 = 1
 ORDER BY SOM.LINENO

SELECT * FROM ARM_CUST_GUARANTY_MST MMM
WHERE CUSTOMERMCODE='22112'

SELECT * FROM SOMGUARANTYSTATUSCODE;
SELECT * FROM ARM_GUARANTY_SITUATION;
--客戶角度
--關聯客戶
SELECT * FROM SOMGROUP;
SELECT * FROM SOMGROUPCREDITPAYMENTTERM;
--客戶主黨
SELECT * FROM SOM_CUSTOMER_MASTER;
SELECT * FROM SCSEMPDATA
select distinct empno, empname from scsempdata;
select b.CUSTOMERMCODE, b.headcode, b.prop_id FROM som_doc_upLoad b WHERE type = 'B';
select * FROM som_doc_upLoad b WHERE type = 'B';







