-- 上傳檔案 SOM_DOC_UPLOAD

SELECT LLL.CUSTOMERMCODE,LLL.HEADCODE,LLL.PROP_ID FROM SOM_DOC_UPLOAD LLL

SELECT *
FROM SOM_DOC_UPLOAD B
WHERE 1=1
AND B.TYPE = 'B' FOR UPDATE 

SELECT b.customermcode, b.headcode, b.prop_id
          FROM som_doc_upload b
         WHERE 1 = 1
           AND b.type = 'B'

SELECT MST.* FROM ARM_CUST_GUARANTY_MST MST,
              SOM_CUSTOMER_MASTER CM,
              SOMGUARANTYSTATUSCODE GSC,
              ARM_GUARANTY_SITUATION AGS
WHERE 1=1
AND MST.PROP_ID='3'
AND MST.CUSTOMERMCODE='22112'
AND MST.CUSTOMERMCODE <> 0
AND MST.CUSTOMERMCODE = CM.CUSTOMERMCODE(+)
AND MST.PROP_ID = CM.PROP_ID(+)

AND MST.GUARANTY_STATUS = GSC.GUARANTYSTATUS
AND MST.GUARANTY_SITUATION = AGS.GUARANTY_SITUATION_CODE
AND AGS.GUARANTY_SITUATION_TYPE ='H'

GROUP BY MST.HEADCODE


-- 上傳檔案


