SELECT MT.COMPANY_CODE AS COMPANY_C,
       MT.SLIP_NO AS SLIP_MO,
       MT.FIX_TYPE AS FIX_TYPE,
       FS1.LABEL AS SERVICE_T,
       OOG.ORG_NAME AS 部門名稱, 
       PC.PROCESS_DESC AS 工單狀態,
       TO_CHAR(MT.WORK_DATE, 'DD-MON-YY') AS 施工日,
       MT.WORK_EMP_NO AS 施工人員,
       FS2.LABEL AS 解決方式,
       TO_CHAR(MT.REGISTER_DATE,
               'DD-MON-YY',
               'NLS_DATE_LANGUAGE = American') AS 報修日期
  FROM TBS_MAJ.FIX_MT           MT,
       TBS_MAJ.FIX_SETTING      FS1,
       TBS_MAJ.FIX_SETTING      FS2,
       TBS_MAJ.FIX_PROCESS_CODE PC,
       TBS_MAJ.FIX_ORG_ORG_GRP  OOG
 WHERE 1 = 1
   AND MT.SERVICE_TYPE = FS1.VALUE(+)
   AND FS1.BU_CODE(+) ='TW'
   AND FS1.KEY(+) = 'SERVICE_TYPE_' || MT.FIX_TYPE
   AND FS1.VALUE(+) = MT.SERVICE_TYPE
   AND FS2.BU_CODE(+) ='TW'
   AND FS2.KEY(+) = 'SOLUTION'
   AND FS2.VALUE(+) = MT.SOLUTIONS_CODE
   AND PC.BU_CODE(+) ='TW'
   AND PC.PROCESS_CODE(+) = MT.PROCESS_CODE
   AND OOG.BU_ID(+) ='TW'
   AND OOG.ORG_ID(+) = MT.DEPT_CODE
 
