SELECT * FROM RPT_CONDITION  FOR UPDATE

SELECT * FROM RPT_CONDITION.DEFAULT_VALUE

SELECT * FROM MST_TABLE_MAPPING WHERE TABLE_NAME='RPCH' FOR UPDATE

SELECT * FROM MST_EMPLOYEE WHERE EMP_NO='8566'

SELECT * FROM RPT_REPORT_INFO FOR UPDATE;

SELECT * FROM SCS_USER_GROUP_FUNC

SELECT * FROM SCS_USER_GROUP

SELECT * FROM SYS_MENU_TREE FOR UPDATE

1. EXCEL 回傳 分頁有值

SELECT * FROM MST_TABLE_MAPPING WHERE TABLE_NAME='RPCH' FOR UPDATE

SELECT * FROM RPT_TITLE WHERE 1=1 FOR UPDATE

SELECT * FROM RPT_CONTENT_MST FOR UPDATE

SELECT * FROM SYS_KEY_SETTING SK WHERE SK.KEY_CODE LIKE '%rpch.er%' for update
CP_RGM
-- LOG
SELECT * FROM SYS_QUERY_LOG ORDER BY QUERY_DATE DESC
SELECT * FROM SYS_QUERY_LOG_DTL LD WHERE LOG_ID='4028516078257fc401787cc255f50013'
ALTER TABLE SYS_QUERY_LOG ADD  TRACING VARCHAR2(300)
comment on column SYS_QUERY_LOG.TRACING      is '瀏覽紀錄';

ALTER TABLE SYS_QUERY_LOG MODIFY  QUERY_EMP_NO VARCHAR2(25) NOT NULL




SELECT * FROM RPT_CONTENT_DTL 

Q1 記LOG時間點?
A. 整個查完已後

Q2 新增欄位 USER 查詢條件
A 有分析得價值



 
   
   SELECT * FROM TBS_MAJ.FIX_PROCESS_CODE PC
   SELECT * FROM TBS_MAJ.FIX_SETTING FS2 WHERE FS2.KEY='SOLUTION'
   
   SELECT * FROM TBS_MAJ.FIX_ORG_ORG_GRP OOG WHERE 1=1
   <table>
<tr>
    <td>工單公司</td>
    <td>工單單號</td>
    <td>類型</td>
    <td>服務類型</td>
    <td>部門</td>
    <td>狀態</td>
    <td>工作日</td>
    <td>施工人員</td>
    <td>解決方式</td>
    <td>註冊日期</td>
</tr>
</table>
