-- BC ½Õ¾ã«O©T
warrantyCode
SELECT * FROM FIX_MT MT WHERE SLIP_NO = 'R201207071'

SELECT FA.WARRANTY_DATE ,FA.WARRANTY_CODE , FA.* FROM FIX_ARTICLE FA  WHERE SLIP_NO = 'R201207071';

SELECT * FROM FIX_SETTING WHERE KEY='WARRANTY_CODE'
2
UPDATE TBS_MAJ.FIX_ARTICLE FA  SET FA.WARRANTY_CODE='2' WHERE SLIP_NO = 'R201207071';



